parameters:
  k8sNamespace: ''
  imagePullSecret: ''
  dockerRegistryServiceConnection: ''
  chartArtifactName: ''
  environment: ''
  values: ''

jobs:
- deployment: Deploy
  displayName: Deploy
  environment: '${{ parameters.environment }}'
  variables:
    overrideFile: 'secret.ci.yaml'
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: ${{ parameters.chartArtifactName }}

        - task: KubernetesManifest@0
          displayName: Create imagePullSecret
          inputs:
            action: createSecret
            namespace: ${{ parameters.k8sNamespace }}
            secretName: ${{ parameters.imagePullSecret }}
            dockerRegistryEndpoint: ${{ parameters.dockerRegistryServiceConnection }}

        - powershell: echo "${{ parameters.values }}" > $(overrideFile)

        - task: KubernetesManifest@0
          displayName: Bake manifests
          name: bake
          inputs:
            action: bake
            namespace: ${{ parameters.k8sNamespace }}
            helmChart: $(Pipeline.Workspace)/${{ parameters.chartArtifactName }}
            overrideFiles: |
              $(overrideFile)

        - task: KubernetesManifest@0
          displayName: Deploy to Kubernetes cluster
          inputs:
            action: deploy
            namespace: ${{ parameters.k8sNamespace }}
            manifests: |
              $(bake.manifestsBundle)
            imagePullSecrets: |
              ${{ parameters.imagePullSecret }}
